spring:
    application:
        name: graphql-playground

    graphql:
        schema:
            locations: classpath:graphql/**/

        http:
            path: /graphql

        graphiql:
            enabled: true
            path: /graphiql

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true